# HW_1

In [20]:
from numpy import arange, zeros, random, dot, linalg, transpose, multiply, subtract, square, sqrt
import numpy as np

In [21]:
vector = arange(1, 11)
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
print(f'Вектор: \n{vector}\n')

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
Вектор: 
[ 1  2  3  4  5  6  7  8  9 10]



In [22]:
matrix = zeros((3, 3))
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
print(f'Матриця: \n{matrix}\n')

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
Матриця: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [23]:
random_matrix = random.randint(1, 11, size=(5, 5))
print(
    '3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.')
print(f'Матриця: \n{random_matrix}\n')

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
Матриця: 
[[ 8 10  9  5  1]
 [ 3  7  3 10  2]
 [ 3  4  3  6  7]
 [ 7  9  6  9  8]
 [ 4  9  2  4  5]]



In [24]:
random_matrix = random.rand(4, 4)
print(
    '4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
print(f'Матриця: \n{random_matrix}\n')

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
Матриця: 
[[0.62556171 0.74038027 0.86205295 0.50245162]
 [0.88496239 0.70099784 0.47341885 0.72507392]
 [0.45603682 0.87919442 0.66652662 0.51751058]
 [0.21582302 0.4619295  0.48554583 0.06439285]]



In [25]:
array_1 = random.randint(1, 11, size=5)
array_2 = random.randint(1, 11, size=5)
sum = array_1 + array_2
sub = array_1 - array_2
multiplication = array_1 * array_2
print(
    '5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
print(f'Вектор 1: {array_1}')
print(f'Вектор 2: {array_2}')
print(f'Сума: {sum}')
print(f'Різниця: {sub}')
print(f'Добуток: {multiplication}\n')

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
Вектор 1: [3 2 5 3 6]
Вектор 2: [5 3 8 3 5]
Сума: [ 8  5 13  6 11]
Різниця: [-2 -1 -3  0  1]
Добуток: [15  6 40  9 30]



In [26]:
vector_1 = random.randint(1, 11, size=7)
vector_2 = random.randint(1, 11, size=7)
scalar = dot(vector_1, vector_2)
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
print(f'Вектор 1: {vector_1}')
print(f'Вектор 2: {vector_2}')
print(f'Cкалярний добуток: {scalar}\n')

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
Вектор 1: [9 4 9 3 3 8 6]
Вектор 2: [7 7 1 3 4 6 8]
Cкалярний добуток: 217



In [27]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 3))
multiplication = dot(matrix_1, matrix_2)
print(
    '7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Результат множення матриць: \n{multiplication}\n')

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
Матриця 1: 
[[5 5]
 [4 7]]
Матриця 2: 
[[ 2 10 10]
 [ 3  3  5]]
Результат множення матриць: 
[[25 65 75]
 [29 61 75]]



In [28]:
matrix = random.randint(1, 11, size=(3, 3))
print(
    '8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
print(f'Матриця: \n{matrix}')
try:
    inv_matrix = linalg.inv(matrix)
    print(f'Обернена матриця: \n{inv_matrix}\n')
except linalg.LinAlgError:
    print(f'Обернена матриця не існує\n')

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
Матриця: 
[[ 1  4  2]
 [ 1  1  1]
 [ 2  9 10]]
Обернена матриця: 
[[-0.05882353  1.29411765 -0.11764706]
 [ 0.47058824 -0.35294118 -0.05882353]
 [-0.41176471  0.05882353  0.17647059]]



In [29]:
matrix = random.randint(1, 11, size=(4, 4))
trans_matrix = transpose(matrix)
print(
    '9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
print(f'Матриця: \n{matrix}')
print(f'Транспонована матриця: \n{trans_matrix}\n')

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
Матриця: 
[[10  7  6 10]
 [ 3  9  4  1]
 [ 9  6  6  4]
 [ 2  6  3  7]]
Транспонована матриця: 
[[10  3  9  2]
 [ 7  9  6  6]
 [ 6  4  6  3]
 [10  1  4  7]]



In [30]:
matrix = random.randint(1, 11, size=(3, 4))
vector = random.randint(1, 11, size=4)
result_vector = dot(matrix, vector)
print(
    '10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.')
print(f'Матриця: \n{matrix}')
print(f'Вектор: {vector}')
print(f'Результат множення матриці на вектор: {result_vector}\n')

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
Матриця: 
[[ 6  2  3 10]
 [ 1  7  9  2]
 [ 6  1  9 10]]
Вектор: [5 4 3 7]
Результат множення матриці на вектор: [117  74 131]



In [31]:
matrix = random.rand(2, 3)
vector = random.rand(3)
result_vector = dot(matrix, vector)
print(
    '11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.')
print(f'Матриця: \n{matrix}')
print(f'Вектор: {vector}')
print(f'Результат множення матриці на вектор: {result_vector}\n')

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
Матриця: 
[[0.05098952 0.76176371 0.25408051]
 [0.52186081 0.98842586 0.45037525]]
Вектор: [0.68677991 0.26376719 0.85912859]
Результат множення матриці на вектор: [0.45423468 1.00604808]



In [32]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 2))
elementwise = multiply(matrix_1, matrix_2)
print(
    '12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Результат поелементного множення матриць: \n{elementwise}\n')

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
Матриця 1: 
[[9 1]
 [9 3]]
Матриця 2: 
[[4 1]
 [4 1]]
Результат поелементного множення матриць: 
[[36  1]
 [36  3]]



In [33]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 2))
product = dot(matrix_1, matrix_2)
print(
    '13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Добуток матриць: \n{product}\n')

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
Матриця 1: 
[[4 8]
 [5 6]]
Матриця 2: 
[[8 1]
 [5 1]]
Добуток матриць: 
[[72 12]
 [70 11]]



In [34]:
matrix = random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix)
print(
    '14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.')
print(f'Матриця: \n{matrix}')
print(f'Сума елементів матриці: {sum_elements}\n')

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
Матриця: 
[[26 34 58 31 87]
 [ 8 56 20 46 12]
 [62 33 84 42 59]
 [19 75 65 70 25]
 [15 89 40 26 67]]
Сума елементів матриці: 1149



In [35]:
matrix_1 = random.randint(1, 11, size=(4, 4))
matrix_2 = random.randint(1, 11, size=(4, 4))
product = subtract(matrix_1, matrix_2)
print(
    '15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Різниця матриць: \n{product}\n')

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
Матриця 1: 
[[ 8 10  2  8]
 [ 7  1 10  8]
 [ 4  1  2  7]
 [ 1  8  4  4]]
Матриця 2: 
[[ 6 10  3  3]
 [ 7  9  1  7]
 [ 2  7  5  5]
 [10  1  4  8]]
Різниця матриць: 
[[ 2  0 -1  5]
 [ 0 -8  9  1]
 [ 2 -6 -3  2]
 [-9  7  0 -4]]



In [36]:
matrix = random.rand(3, 3)
row_sums = np.sum(matrix, axis=1, keepdims=True)
print(
    '16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
print(f'Матриця: \n{matrix}')
print(f'Cума елементів кожного рядка матриці: \n{row_sums}\n')

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
Матриця: 
[[0.76950948 0.3184035  0.20325069]
 [0.51043142 0.53180869 0.28116826]
 [0.19909186 0.05389568 0.38525345]]
Cума елементів кожного рядка матриці: 
[[1.29116366]
 [1.32340837]
 [0.63824098]]



In [37]:
matrix = random.randint(-10, 11, size=(3, 4))
square_matrix = square(matrix)
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
print(f'Матриця: \n{matrix}')
print(f'Матриця з квадратами чисел: \n{square_matrix}\n')

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
Матриця: 
[[ 3  1  2 -6]
 [-9  7 -3 -8]
 [ 8 -5 -5  1]]
Матриця з квадратами чисел: 
[[ 9  1  4 36]
 [81 49  9 64]
 [64 25 25  1]]



In [38]:
vector = random.randint(1, 51, size=4)
sqrt_vector = sqrt(vector)
print(
    '18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
print(f'Вектор: {vector}')
print(f'Вектор з квадратними коренями: \n{sqrt_vector}\n')

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
Вектор: [ 4 14  5  8]
Вектор з квадратними коренями: 
[2.         3.74165739 2.23606798 2.82842712]

