# Editor

In [1]:
from numpy import arange, zeros, random, dot, linalg, transpose, multiply, subtract, square, sqrt
import numpy as np

In [2]:
vector = arange(1, 11)
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
print(f'Вектор: \n{vector}\n')

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
Вектор: 
[ 1  2  3  4  5  6  7  8  9 10]



In [3]:
matrix = zeros((3, 3))
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
print(f'Матриця: \n{matrix}\n')

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
Матриця: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [4]:
random_matrix = random.randint(1, 11, size=(5, 5))
print(
    '3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.')
print(f'Матриця: \n{random_matrix}\n')

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
Матриця: 
[[ 6  5 10  5  7]
 [ 7  6  3 10  3]
 [ 5  8  7  3  2]
 [ 3  1  9  1 10]
 [ 9  7  6  8  9]]



In [5]:
random_matrix = random.rand(4, 4)
print(
    '4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
print(f'Матриця: \n{random_matrix}\n')

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
Матриця: 
[[0.30702622 0.59968255 0.86916111 0.56625095]
 [0.79308692 0.73856317 0.74637883 0.62758834]
 [0.77106283 0.22819251 0.63763046 0.47509069]
 [0.46127829 0.49947897 0.9869612  0.28448579]]



In [6]:
array_1 = random.randint(1, 11, size=5)
array_2 = random.randint(1, 11, size=5)
sum = array_1 + array_2
sub = array_1 - array_2
multiplication = array_1 * array_2
print(
    '5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
print(f'Вектор 1: {array_1}')
print(f'Вектор 2: {array_2}')
print(f'Сума: {sum}')
print(f'Різниця: {sub}')
print(f'Добуток: {multiplication}\n')

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
Вектор 1: [6 2 8 1 4]
Вектор 2: [6 1 9 2 3]
Сума: [12  3 17  3  7]
Різниця: [ 0  1 -1 -1  1]
Добуток: [36  2 72  2 12]



In [7]:
vector_1 = random.randint(1, 11, size=7)
vector_2 = random.randint(1, 11, size=7)
scalar = dot(vector_1, vector_2)
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
print(f'Вектор 1: {vector_1}')
print(f'Вектор 2: {vector_2}')
print(f'Cкалярний добуток: {scalar}\n')

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
Вектор 1: [3 8 9 2 2 4 1]
Вектор 2: [ 8  4  5 10  2  2  3]
Cкалярний добуток: 136



In [8]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 3))
multiplication = dot(matrix_1, matrix_2)
print(
    '7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Результат множення матриць: \n{multiplication}\n')

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
Матриця 1: 
[[8 6]
 [7 3]]
Матриця 2: 
[[10  3  2]
 [ 3 10  4]]
Результат множення матриць: 
[[98 84 40]
 [79 51 26]]



In [9]:
matrix = random.randint(1, 11, size=(3, 3))
print(
    '8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
print(f'Матриця: \n{matrix}')
try:
    inv_matrix = linalg.inv(matrix)
    print(f'Обернена матриця: \n{inv_matrix}\n')
except linalg.LinAlgError:
    print(f'Обернена матриця не існує\n')

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
Матриця: 
[[8 3 5]
 [3 2 4]
 [6 8 6]]
Обернена матриця: 
[[ 0.24390244 -0.26829268 -0.02439024]
 [-0.07317073 -0.2195122   0.20731707]
 [-0.14634146  0.56097561 -0.08536585]]



In [10]:
matrix = random.randint(1, 11, size=(4, 4))
trans_matrix = transpose(matrix)
print(
    '9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
print(f'Матриця: \n{matrix}')
print(f'Транспонована матриця: \n{trans_matrix}\n')

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
Матриця: 
[[ 5  9  5  2]
 [ 7  9  4  2]
 [10  3  2  1]
 [ 1  1  6  6]]
Транспонована матриця: 
[[ 5  7 10  1]
 [ 9  9  3  1]
 [ 5  4  2  6]
 [ 2  2  1  6]]



In [11]:
matrix = random.randint(1, 11, size=(3, 4))
vector = random.randint(1, 11, size=4)
result_vector = dot(matrix, vector)
print(
    '10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.')
print(f'Матриця: \n{matrix}')
print(f'Вектор: {vector}')
print(f'Результат множення матриці на вектор: {result_vector}\n')

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
Матриця: 
[[ 6  6  9  4]
 [ 5  8 10  9]
 [ 4  9  4  5]]
Вектор: [6 7 7 6]
Результат множення матриці на вектор: [165 210 145]



In [12]:
matrix = random.rand(2, 3)
vector = random.rand(3)
result_vector = dot(matrix, vector)
print(
    '11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.')
print(f'Матриця: \n{matrix}')
print(f'Вектор: {vector}')
print(f'Результат множення матриці на вектор: {result_vector}\n')

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
Матриця: 
[[0.2749696  0.37818054 0.65689657]
 [0.27484071 0.06534202 0.4049423 ]]
Вектор: [0.4039118  0.58919505 0.02626174]
Результат множення матриці на вектор: [0.35113682 0.16014509]



In [13]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 2))
elementwise = multiply(matrix_1, matrix_2)
print(
    '12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Результат поелементного множення матриць: \n{elementwise}\n')

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
Матриця 1: 
[[2 8]
 [3 9]]
Матриця 2: 
[[ 5 10]
 [ 6  9]]
Результат поелементного множення матриць: 
[[10 80]
 [18 81]]



In [14]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 2))
product = dot(matrix_1, matrix_2)
print(
    '13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Добуток матриць: \n{product}\n')

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
Матриця 1: 
[[ 2 10]
 [ 8  9]]
Матриця 2: 
[[3 4]
 [9 1]]
Добуток матриць: 
[[ 96  18]
 [105  41]]



In [15]:
matrix = random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix)
print(
    '14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.')
print(f'Матриця: \n{matrix}')
print(f'Сума елементів матриці: {sum_elements}\n')

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
Матриця: 
[[ 71  41   4  45  64]
 [ 82  36  20  16  98]
 [100  73  61  63  79]
 [ 98  73  24  85  66]
 [ 38  74  82  12  22]]
Сума елементів матриці: 1427



In [16]:
matrix_1 = random.randint(1, 11, size=(4, 4))
matrix_2 = random.randint(1, 11, size=(4, 4))
product = subtract(matrix_1, matrix_2)
print(
    '15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Різниця матриць: \n{product}\n')

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
Матриця 1: 
[[ 8  7  5  3]
 [ 2 10  9  6]
 [ 9 10 10  7]
 [ 2  5  6  5]]
Матриця 2: 
[[ 1  2  9  8]
 [ 9  1  1  7]
 [ 7  3  5 10]
 [ 1  6  1  4]]
Різниця матриць: 
[[ 7  5 -4 -5]
 [-7  9  8 -1]
 [ 2  7  5 -3]
 [ 1 -1  5  1]]



In [17]:
matrix = random.rand(3, 3)
row_sums = np.sum(matrix, axis=1, keepdims=True)
print(
    '16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
print(f'Матриця: \n{matrix}')
print(f'Cума елементів кожного рядка матриці: \n{row_sums}\n')

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
Матриця: 
[[0.35175417 0.08268618 0.61452604]
 [0.21245373 0.81768767 0.99113376]
 [0.53859299 0.53717589 0.71976028]]
Cума елементів кожного рядка матриці: 
[[1.04896638]
 [2.02127516]
 [1.79552916]]



In [18]:
matrix = random.randint(-10, 11, size=(3, 4))
square_matrix = square(matrix)
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
print(f'Матриця: \n{matrix}')
print(f'Матриця з квадратами чисел: \n{square_matrix}\n')

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
Матриця: 
[[ 8  1  9 -4]
 [-9  1  7 -9]
 [ 2  3 -2 -9]]
Матриця з квадратами чисел: 
[[64  1 81 16]
 [81  1 49 81]
 [ 4  9  4 81]]



In [19]:
vector = random.randint(1, 51, size=4)
sqrt_vector = sqrt(vector)
print(
    '18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
print(f'Вектор: {vector}')
print(f'Вектор з квадратними коренями: \n{sqrt_vector}\n')

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
Вектор: [11 48 16 24]
Вектор з квадратними коренями: 
[3.31662479 6.92820323 4.         4.89897949]



# Getting Started Notebook

Welcome to Datalore! This tutorial will help you understand the basics of the platform and start working with it.

**Datalore** is the collaborative data science platform developed by JetBrains.

This tutorial is a great place to learn about major Datalore features. If you want more information, you can:
- Visit our [Documentation](https://www.jetbrains.com/help/datalore/datalore-quickstart.html) for guides on specific features.
- Subscribe to the [Datalore's blog](https://blog.jetbrains.com/datalore/). You will receive emails about feature announcements and Datalore tutorials!

## Watch this 2-minute Datalore overview video!
<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/Quick+Datalore+Overview.mp4" type="video/mp4">

</video></div>

In [20]:
message = "😍🚀🙏🏻"

In [21]:
print("Hi, Datalore! I'm feeling " + message)

Hi, Datalore! I'm feeling 😍🚀🙏🏻


💡 This tutorial is split into **worksheets**, and it is the first cool feature of the Datalore Editor!
Just navigate through the tabs at the bottom of the editor or use the Table of contents on the left-hand sidebar.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/worksheets.png" width = 900 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Video tutorial: Notebook Editor

<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/1_Datalore_Editor+Overview.mp4" type="video/mp4">

</video></div>

## Cells

Inside the notebook you can add:

- **Python code cells**, where you can use powerful coding assistance features such as code completion, quick-fixes, documentation popups, refactorings, and more. Code cells also support IPython magic commands.
- **SQL cells** with code completion for both SQL syntax and database column names. The query result of a SQL cell is automatically transferred to the pandas dataframe.
- **Markdown cells** with a text formatting toolbar and LaTeX support.
- **Interactive controls** such as Dropdowns, Sliders, Text inputs, Checkboxes, Date pickers, Metric cells, Chart cells, and visibility controls.

To add a new cell, hover over the bottom center of a cell and choose the cell type you want to add. 
Check out the [Shortcuts 101](./#Shortcuts-101) tab for a collection of the most useful shortcuts in Datalore.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/add_cell2.png" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Essential tools on the Left-hand sidebar

You can access the most important Datalore features from the left-hand sidebar menu:
- Configure the environment and install additional packages inside the **Environment** tab.
- Upload data files and connect databases and S3 buckets from the **Attached data** tab.
- See machine statistics, and configure Background computation and Scheduled runs from the **Computation** tab.
- Navigate through the notebook using the **Table of contents** tab.
- Browse variable contents from the **Variable viewer** tab.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/left_sidebar2.png" title = "Computation tab in the left-hand sidebar" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;" /></div>

**Now please switch to the second worksheet tab: Data**

# Data

# Environment

# Sharing

# Reporting

# Automations

# Tutorials