# Editor

In [79]:
from numpy import arange, zeros, random, dot, linalg, transpose, multiply, subtract, square, sqrt
import numpy as np

In [80]:
vector = arange(1, 11)
print('1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
print(f'Вектор: \n{vector}\n')

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
Вектор: 
[ 1  2  3  4  5  6  7  8  9 10]



In [81]:
matrix = zeros((3, 3))
print('2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
print(f'Матриця: \n{matrix}\n')

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
Матриця: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [82]:
random_matrix = random.randint(1, 11, size=(5, 5))
print(
    '3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.')
print(f'Матриця: \n{random_matrix}\n')

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
Матриця: 
[[ 3  6  6  7  2]
 [ 1  9  6  5  4]
 [ 6  8 10  6  7]
 [ 4  8  6  1  3]
 [ 6  3  3  2  9]]



In [83]:
random_matrix = random.rand(4, 4)
print(
    '4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
print(f'Матриця: \n{random_matrix}\n')

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
Матриця: 
[[0.08054729 0.03698807 0.12849522 0.94131116]
 [0.34450729 0.08907403 0.15746486 0.08555533]
 [0.78407978 0.81937871 0.54557663 0.74585082]
 [0.59953105 0.9410038  0.40099061 0.75412827]]



In [84]:
array_1 = random.randint(1, 11, size=5)
array_2 = random.randint(1, 11, size=5)
sum = array_1 + array_2
sub = array_1 - array_2
multiplication = array_1 * array_2
print(
    '5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
print(f'Вектор 1: {array_1}')
print(f'Вектор 2: {array_2}')
print(f'Сума: {sum}')
print(f'Різниця: {sub}')
print(f'Добуток: {multiplication}\n')

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
Вектор 1: [ 8 10  4  9  9]
Вектор 2: [ 3  3  2 10  4]
Сума: [11 13  6 19 13]
Різниця: [ 5  7  2 -1  5]
Добуток: [24 30  8 90 36]



In [85]:
vector_1 = random.randint(1, 11, size=7)
vector_2 = random.randint(1, 11, size=7)
scalar = dot(vector_1, vector_2)
print('6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
print(f'Вектор 1: {vector_1}')
print(f'Вектор 2: {vector_2}')
print(f'Cкалярний добуток: {scalar}\n')

6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
Вектор 1: [4 3 7 1 3 5 1]
Вектор 2: [3 7 3 7 4 9 9]
Cкалярний добуток: 127



In [86]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 3))
multiplication = dot(matrix_1, matrix_2)
print(
    '7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Результат множення матриць: \n{multiplication}\n')

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
Матриця 1: 
[[ 5 10]
 [ 3  1]]
Матриця 2: 
[[1 5 3]
 [2 9 9]]
Результат множення матриць: 
[[ 25 115 105]
 [  5  24  18]]



In [87]:
matrix = random.randint(1, 11, size=(3, 3))
print(
    '8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
print(f'Матриця: \n{matrix}')
try:
    inv_matrix = linalg.inv(matrix)
    print(f'Обернена матриця: \n{inv_matrix}\n')
except linalg.LinAlgError:
    print(f'Обернена матриця не існує\n')

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
Матриця: 
[[10 10 10]
 [10  2  5]
 [10  2  9]]
Обернена матриця: 
[[-0.025    0.21875 -0.09375]
 [ 0.125    0.03125 -0.15625]
 [ 0.      -0.25     0.25   ]]



In [88]:
matrix = random.randint(1, 11, size=(4, 4))
trans_matrix = transpose(matrix)
print(
    '9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
print(f'Матриця: \n{matrix}')
print(f'Транспонована матриця: \n{trans_matrix}\n')

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
Матриця: 
[[10  3 10  6]
 [10  2  9  9]
 [ 3  6  8 10]
 [ 9  8  6  3]]
Транспонована матриця: 
[[10 10  3  9]
 [ 3  2  6  8]
 [10  9  8  6]
 [ 6  9 10  3]]



In [89]:
matrix = random.randint(1, 11, size=(3, 4))
vector = random.randint(1, 11, size=4)
result_vector = dot(matrix, vector)
print(
    '10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.')
print(f'Матриця: \n{matrix}')
print(f'Вектор: {vector}')
print(f'Результат множення матриці на вектор: {result_vector}\n')

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
Матриця: 
[[ 6  7 10  7]
 [ 7  1  7  1]
 [ 6  9  1  4]]
Вектор: [9 5 4 4]
Результат множення матриці на вектор: [157 100 119]



In [90]:
matrix = random.rand(2, 3)
vector = random.rand(3)
result_vector = dot(matrix, vector)
print(
    '11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.')
print(f'Матриця: \n{matrix}')
print(f'Вектор: {vector}')
print(f'Результат множення матриці на вектор: {result_vector}\n')

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
Матриця: 
[[0.83510862 0.68920196 0.0371938 ]
 [0.92987486 0.82302    0.88195311]]
Вектор: [0.00644033 0.10441639 0.55716414]
Результат множення матриці на вектор: [0.09806541 0.58331813]



In [91]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 2))
elementwise = multiply(matrix_1, matrix_2)
print(
    '12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Результат поелементного множення матриць: \n{elementwise}\n')

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
Матриця 1: 
[[8 9]
 [4 4]]
Матриця 2: 
[[5 4]
 [3 4]]
Результат поелементного множення матриць: 
[[40 36]
 [12 16]]



In [92]:
matrix_1 = random.randint(1, 11, size=(2, 2))
matrix_2 = random.randint(1, 11, size=(2, 2))
product = dot(matrix_1, matrix_2)
print(
    '13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Добуток матриць: \n{product}\n')

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
Матриця 1: 
[[8 8]
 [4 4]]
Матриця 2: 
[[7 3]
 [2 5]]
Добуток матриць: 
[[72 64]
 [36 32]]



In [93]:
matrix = random.randint(1, 101, size=(5, 5))
sum_elements = np.sum(matrix)
print(
    '14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.')
print(f'Матриця: \n{matrix}')
print(f'Сума елементів матриці: {sum_elements}\n')

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
Матриця: 
[[66 85  3  8 42]
 [90  7 90 17 82]
 [15 65  2 73 81]
 [45 18 99 72 66]
 [40 48 64 32 49]]
Сума елементів матриці: 1259



In [94]:
matrix_1 = random.randint(1, 11, size=(4, 4))
matrix_2 = random.randint(1, 11, size=(4, 4))
product = subtract(matrix_1, matrix_2)
print(
    '15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.')
print(f'Матриця 1: \n{matrix_1}')
print(f'Матриця 2: \n{matrix_2}')
print(f'Різниця матриць: \n{product}\n')

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
Матриця 1: 
[[3 7 8 1]
 [8 1 6 3]
 [1 6 5 7]
 [5 6 5 3]]
Матриця 2: 
[[1 5 9 3]
 [2 3 9 2]
 [1 9 7 9]
 [2 4 8 3]]
Різниця матриць: 
[[ 2  2 -1 -2]
 [ 6 -2 -3  1]
 [ 0 -3 -2 -2]
 [ 3  2 -3  0]]



In [95]:
matrix = random.rand(3, 3)
row_sums = np.sum(matrix, axis=1, keepdims=True)
print(
    '16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
print(f'Матриця: \n{matrix}')
print(f'Cума елементів кожного рядка матриці: \n{row_sums}\n')

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
Матриця: 
[[0.80513643 0.20177458 0.29649347]
 [0.87856924 0.37678925 0.70889989]
 [0.41783686 0.35936055 0.31195316]]
Cума елементів кожного рядка матриці: 
[[1.30340449]
 [1.96425838]
 [1.08915056]]



In [96]:
matrix = random.randint(-10, 11, size=(3, 4))
square_matrix = square(matrix)
print('17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
print(f'Матриця: \n{matrix}')
print(f'Матриця з квадратами чисел: \n{square_matrix}\n')

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
Матриця: 
[[ 9 -4  0 -3]
 [-2 10  1  7]
 [-1 -3  7 -8]]
Матриця з квадратами чисел: 
[[ 81  16   0   9]
 [  4 100   1  49]
 [  1   9  49  64]]



In [97]:
vector = random.randint(1, 51, size=4)
sqrt_vector = sqrt(vector)
print(
    '18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
print(f'Вектор: {vector}')
print(f'Вектор з квадратними коренями: \n{sqrt_vector}\n')

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
Вектор: [41  5 22 13]
Вектор з квадратними коренями: 
[6.40312424 2.23606798 4.69041576 3.60555128]



# Getting Started Notebook

Welcome to Datalore! This tutorial will help you understand the basics of the platform and start working with it.

**Datalore** is the collaborative data science platform developed by JetBrains.

This tutorial is a great place to learn about major Datalore features. If you want more information, you can:
- Visit our [Documentation](https://www.jetbrains.com/help/datalore/datalore-quickstart.html) for guides on specific features.
- Subscribe to the [Datalore's blog](https://blog.jetbrains.com/datalore/). You will receive emails about feature announcements and Datalore tutorials!

## Watch this 2-minute Datalore overview video!
<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/Quick+Datalore+Overview.mp4" type="video/mp4">

</video></div>

In [98]:
message = "😍🚀🙏🏻"

In [99]:
print("Hi, Datalore! I'm feeling " + message)

Hi, Datalore! I'm feeling 😍🚀🙏🏻


💡 This tutorial is split into **worksheets**, and it is the first cool feature of the Datalore Editor!
Just navigate through the tabs at the bottom of the editor or use the Table of contents on the left-hand sidebar.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/worksheets.png" width = 900 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Video tutorial: Notebook Editor

<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/1_Datalore_Editor+Overview.mp4" type="video/mp4">

</video></div>

## Cells

Inside the notebook you can add:

- **Python code cells**, where you can use powerful coding assistance features such as code completion, quick-fixes, documentation popups, refactorings, and more. Code cells also support IPython magic commands.
- **SQL cells** with code completion for both SQL syntax and database column names. The query result of a SQL cell is automatically transferred to the pandas dataframe.
- **Markdown cells** with a text formatting toolbar and LaTeX support.
- **Interactive controls** such as Dropdowns, Sliders, Text inputs, Checkboxes, Date pickers, Metric cells, Chart cells, and visibility controls.

To add a new cell, hover over the bottom center of a cell and choose the cell type you want to add. 
Check out the [Shortcuts 101](./#Shortcuts-101) tab for a collection of the most useful shortcuts in Datalore.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/add_cell2.png" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Essential tools on the Left-hand sidebar

You can access the most important Datalore features from the left-hand sidebar menu:
- Configure the environment and install additional packages inside the **Environment** tab.
- Upload data files and connect databases and S3 buckets from the **Attached data** tab.
- See machine statistics, and configure Background computation and Scheduled runs from the **Computation** tab.
- Navigate through the notebook using the **Table of contents** tab.
- Browse variable contents from the **Variable viewer** tab.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/left_sidebar2.png" title = "Computation tab in the left-hand sidebar" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;" /></div>

**Now please switch to the second worksheet tab: Data**

# Data

# Working with data
## Video tutorial

<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/2_Working_with_Data.mp4">

</video></div>


## Plug in multiple data sources

In Datalore you can work with **various data sources** together in one notebook. 

You can connect your **SQL databases** (such as MySQL, Snowflake, PostgreSQL, Redshift, etc.), **bucket storages** (AWS S3, GCS buckets), and **files** (any file types) from the interface and further query and join them in one notebook.

To manage all your data, please use the **Attached data** tab in the left-hand sidebar.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/many_datasets2.png" width = 1000 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Reusing data connections

When creating a bucket or a database connection, you’ll be able to reuse it across other notebooks in the same workspace.

You can manage all of the attached data sources from the workspace file system and add new connections directly from the notebook interface.

When you share a notebook or a workspace, your credentials **are not exposed to the environment**.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/manage_datasources2.png" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Persistent file storage

Datalore comes with persistent storage for each notebook. This means you can upload your data files directly to **Notebook files**. If you want to share a file across multiple notebooks, attach **Workspace files** to the notebook and upload it there. Workspace files are mounted under the `/data/workspace_files/` directory.

### Benefits of attaching files to a notebook

- Your workspace file system won't be cluttered with too many files.
- Notebook files are shared automatically when you invite collaborators to the notebook.

Additionally, you can download data to Notebook or Workspace files or to store it in memory using various Python packages and APIs.

## Dataframe exploration

Whenever a pandas dataframe is the result of your cell execution, you get additional tabs in the cell output:
- **Table** – a scrollable table view of your data
- **Raw** – this tab represents the raw output without the ability to scroll the data
- **Visualize** – this tab brings out-of-the box plots to help you visually explore the data
- **Statistics** – this tab provides essential descriptive statistics for your dataframe

### Task: **Run the code cell above** and navigate to the **Visualize** and **Statistics** tabs!

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/statistics_new2.png" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>


In [100]:
import urllib
import pandas as pd

urllib.request.urlretrieve('https://datalore-samples.s3.eu-west-1.amazonaws.com/datalore_gallery_of_samples/Getting+started/gpus.csv', 'gpus.csv')

data = pd.read_csv("gpus.csv")
data

Manufacturer 
 Class 
 Name 
 Year 
 Fab 
 Transistors (mln) 
 Die size 
 Memory size 
 Memory speed 
 GFLOPS 
 TDP 
 
 
 
 
 0 
 Nvidia 
 Desktop 
 GeForce 8300 GS 
 2007 
 80 
 210 
 127 
 512 
 6.4 
 14.4 
 40.0 
 
 
 1 
 Nvidia 
 Desktop 
 GeForce 8400 GS 
 2007 
 80 
 210 
 127 
 512 
 6.4 
 28.8 
 40.0 
 
 
 2 
 Nvidia 
 Desktop 
 GeForce 8400 GS rev.2 
 2007 
 65 
 210 
 86 
 512 
 6.4 
 24.4 
 25.0 
 
 
 3 
 Nvidia 
 Desktop 
 GeForce 8400 GS rev.3 
 2010 
 40 
 260 
 57 
 1024 
 9.6 
 19.7 
 25.0 
 
 
 4 
 Nvidia 
 Desktop 
 GeForce 8500 GT 
 2007 
 80 
 210 
 127 
 1024 
 12.8 
 28.8 
 45.0 
 
 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 ... 
 
 
 490 
 AMD Radeon 
 Datacenter 
 Radeon Instinct MI6 
 2016 
 14 
 5700 
 232 
 16384 
 224.0 
 5800.0 
 150.0 
 
 
 491 
 AMD Radeon 
 Datacenter 
 Radeon Instinct MI8 
 2016 
 28 
 8900 
 596 
 4096 
 512.0 
 8200.0 
 175.0 
 
 
 492 
 AMD Radeon 
 Datacenter 
 Radeon Instinct MI25 
 2016 
 14 
 12500 
 510 
 16384 
 436.2 
 12300.0 
 300.0 
 
 
 493 
 AMD Radeon 
 Datacenter 
 Radeon Instinct MI50 
 2018 
 7 
 13200 
 331 
 16384 
 1024.0 
 13400.0 
 300.0 
 
 
 494 
 AMD Radeon 
 Datacenter 
 Radeon Instinct MI60 
 2018 
 7 
 13200 
 331 
 32768 
 1024.0 
 14725.0 
 300.0 
 
 
 
 495 rows × 11 columns

## Viewing and editing attached files

Double-clicking on a .csv or text file opens it for editing in the right sidebar editor and lets you view the file and edit its contents.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/edit_csv_new2.png" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

If you open a .py script, you will also get smart coding assistance features for editing its contents.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/python_func2.png" width = 600 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

# Environment

# Managing the environment

## Video tutorial

<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/3_Configuring_Environment_in_Datalore.mp4">

</video></div>

## Preconfigured environment

Each notebook in Datalore has an **isolated environment**. This means that when you apply changes to one notebook, they won't affect any of the other notebook environments.

Datalore comes with a lot of **Python libraries pre-installed**.

We've already installed `pandas`, `NumPy`, `sklearn`, `MatplotLib`, and `Seaborn`, so you can start importing the package you need right away.

Datalore supports both the **pip** and **Conda** package managers. Pip is chosen by default, but you can always switch to Conda.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/environment_tab.png" width = 300 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Installing additional libraries

- To install additional libraries, upgrade package versions, and remove libraries, go to *Environment | Explore tab*. The changes will be written into the .yaml file, which will be stored in your Notebook files.
- To install a package from a Git repository, go to *Environment | Repositories*.
- To install any other dependencies (f.e. non-python dependencies), you can modify the `init.sh` file. It will run before the environment is installed.
  
💡 Packages installed via the **Environment** tab are **persisted** when you reopen notebooks. You can also install packages using **pip magic commands** or ***Terminal***, but they won't be persisted.

You can learn more about this in the [Environment manager documentation.](https://www.jetbrains.com/help/datalore/environment.html)

### Task: Install and import the `datasets` library

1. Run the code cell below using `Shift+Enter`.
2. **Click on the prompt in the error log to search for the datasets library. This prompt will open the *Explore tab* of the *Environment manager*.**
3. Click on the datasets library.
4. Click the Install button.
5. Restart the kernel.
6. Rerun the cell.

In [101]:
import datasets

datasets.__version__

ModuleNotFoundError: ModuleNotFoundError: No module named 'datasets'

# Sharing

# Collaborating with your team

## Video tutorial

<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/4_Sharing_Notebooks_and_Workspaces_in_Datalore.mp4">

</video></div>

## Sharing a notebook

In Datalore, you can edit notebooks together with your team in real time.

Click on the Share button in the top-right corner and choose your preferred sharing method:
- Share by sending a link (the simpler option).
- Invite collaborators by email (for more granular permissions).
- Share with groups of collaborators. Please contact your Datalore admins to find out whether you have groups integrated with Datalore.
  
💡 To access notebooks as collaborators, invited users will need to create a Datalore account.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/Sharing2.png" width = 900 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

When sharing a notebook you can provide either edit or view access.
- **Edit access** will allow collaborators to edit code and attached files and run computations.
  
  ⚠️ Note that collaborators will consume the notebook owner's resources.
- **View access** will only allow users to see the real-time representation of the notebook.
  
To track the changes, Datalore has a **built-in version control system** where you can create history checkpoints and revert the notebook to past versions. Check this out via ***Tools | History***.

You can read more about notebook sharing [here](https://www.jetbrains.com/help/datalore/share-a-notebook.html).

### Task: Invite your colleagues to Datalore!

Try out the real-time collaboration feature with your colleagues. Working together can be a lot of fun. 🚀

To **track your collaborator's actions** through the notebook and attached files, click on their avatar in the upper right-hand corner and start following along!

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/Main_teamwork.png" width = 900 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Sharing a workspace

In Datalore, you can create and share workspaces.

Workspaces help you organize your work and allow you to easily share multiple notebooks, data connections, files, and reports with your team.


<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/datalore_gallery_of_samples/Getting+started/workspace.png" width = 300 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

⚠️ Note that the workspace owner's resources will be consumed for all the computations made in the workspace.

# Reporting

# Reporting

## Video tutorial

<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/5_Creating_Interactive_Reports_with_Datalore.mp4">

</video></div>


## Report builder

To share your research results with stakeholders, you can use the Report builder feature via the *Tools* menu section or by clicking the *Build report* button in the upper right-hand corner.

You will be able to:
- Arrange the cells on a canvas to make the report look more dashboard-style.
- Hide specific cell inputs and outputs.
- Publish a static or interactive report.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/Report_builder2.png" width = 900 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

### Task: Create a report out of this notebook!

## Sharing reports
After you publish a report, it will become available under a link. You can then share it with colleagues even if they don't have a Datalore account – the report will be available for them inside the browser. Each report viewer will get a separate copy of the report and will be able to interact with the controls and rerun the report independently.

You can also access **all the workspace reports** from the Published reports section in your Workspace file system.

## Export as PDF, PY, IPYNB

You can export notebooks in multiple formats, including PDF.

Go to the *File* menu tab and select the export option you need.

# Automations

# Automations

## Video tutorial

<div align="center"><video width="800" height="450" controls>

<source src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/6_Creating_Schedules_and_Configuring_Computation_in_Datalore.mp4">

</video></div>

## Scheduled runs

In Datalore, you can schedule your notebook to run on a regular basis. Go to the Computation tab and create a schedule in the Scheduled runs widget. You'll be able to configure the running interval by using the dropdowns or by specifying a cron string.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/scheduling2.png" width = 900 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

### Scheduled report updates

When configuring notebook schedules, you can choose to automatically update published reports, delivering regular updates to your stakeholders.

### Managing the schedules

You can view and edit all the schedules of the workspace from the file system. You'll be able to view your run results and change the scheduling settings.

## Switching between CPU and GPU

When running a notebook, you can choose between available machines according to your needs. The Computation tab will also show you the CPU and RAM load statistics. The computation status bar is located in the bottom right-hand corner of the editor.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/getting-started/videos_new/Changing_machine_type.png" width = 300 border="2" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

## Background computation
 
Switching on Background computation from the Computation tab allows you to keep notebooks running even if you close the browser tab. 

Learn more about Background computation [here](https://helpserver.labs.jb.gg/help/datalore/machine-management.html#computation-modes).

⚠️ Be careful when switching on Background computation, as it will consume your computation quota.

## Shortcuts 101

Datalore supports a wide variety of Jupyter and PyCharm shortcuts. You can access the full list from *Help | Shortcuts* or by pressing `Shift+F1`.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/datalore_gallery_of_samples/Getting+started/Shortcuts.png" width = 300 border="1" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

### Command mode and Editor mode

There are two modes for shortcuts: Command mode and Editor mode.

When editing a cell's content you are in Editor mode. To access Command mode, which allows you to manipulate the cells themselves, press `Esc`. To switch back to Editor mode, press `Enter`.

### Some of the most often used shortcuts include:

- Run the selected cell and select below: `Shift+Enter`.
- Change cell type: `Command+M/Ctrl+M`.
- Undo action: `Command+Z/Ctrl+Z`.
- Delete cell: `DD` (Command mode).
- Insert cell above: `A` (Command mode).
- Insert cell below: `B` (Command mode).
- Copy selected cells: `C` (Command mode).
- Cut selected cells: `X` (Command mode).
- Paste below: `V` (Command mode).

### Command palette

Access quick actions using the Command palette from the Help menu tab.

<div><img src="https://datalore-samples.s3.eu-west-1.amazonaws.com/datalore_gallery_of_samples/Getting+started/Command_palette.png" width = 300 border="1" style="border-color: #d3d3d3; margin-top: 1%;"/></div>

# Tutorials

# Tutorial Gallery, Updates, Contact info

We regularly post tips & tricks on our [blog](https://blog.jetbrains.com/datalore/) and on[Twitter](https://twitter.com/Datalore)! Check them out and subscribe to get the most out of Datalore.

## Basic tutorials

- [Pandas Tutorial: 10 Most Popular Questions for Python Data Frames](https://datalore.jetbrains.com/view/notebook/6gojhrbqOlQNBil7H542XF)
- [Visualization Tutorial With Seaborn](https://datalore.jetbrains.com/view/notebook/v8mLoENq8XTfmStTCLNMV6)
- [Visualization With Pyplot in Datalore](https://datalore.jetbrains.com/view/notebook/Rk9o3SlkJAd47e8plzm0dV)
- [Interactive Controls Tutorial](https://datalore.jetbrains.com/view/notebook/sQPS7uBqNrBiu7t7uQXV74)
- [Lets-Plot Usage Guide](https://datalore.jetbrains.com/view/notebook/nsYaTYEEYG1wGIaqa2bWr5)
- [Exploratory Data Analysis in Practice](https://blog.jetbrains.com/datalore/2022/09/05/exploratory-data-analysis-in-practice/)

## Cool notebook samples

- [10,000,000 Jupyter Notebooks Analyzed](https://datalore.jetbrains.com/view/notebook/F7aMWFiuETFIWCo9BoxAtv)
- [Random Forest, Trees, and Stumps 🌳🌴🌲 A General Overview of Binary Classification Models](https://datalore.jetbrains.com/view/notebook/feUEhlTKRkbohY59fq18fN)

## Webinars
- [Is Your Analysis Reproducible? 5 Ways to Make Your Work Bulletproof With Datalore](https://www.youtube.com/watch?v=MIctg07feIc)
- [5 Tips for Combining Python and SQL in Datalore](https://www.youtube.com/watch?v=5lPTshUFpW8)

## Video Tutorials
- [5 tips for using SQL cells in Datalore](https://www.youtube.com/watch?v=xHlahGVq_BE)
- [5 Tips for Creating Interactive Reports with Python in Datalore](https://www.youtube.com/watch?v=cyYpQMRUOdE)

## How to get support

What really helps us make the Datalore product better is your feedback. Our team is always thankful when you tell us about your experience or report bugs.

Feel free to share your feedback with us and report any issues by:

- Writing a post on our [public forum](https://datalore-forum.jetbrains.com/).
- Emailing us at datalore-enterprise@jetbrains.com.